services:
  postgres:
    container_name: 'py-xls-consumer_postgres'
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres

networks:
  postgres:
    name: py-xls-consumer

volumes:
  postgres: